name: Deploy ShopEasy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --instance-ids i-03d9f6644b43993b8 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["set -e","mkdir -p /tmp/shopeasy-deploy","curl -fL https://raw.githubusercontent.com/nutankumari181121-gif/ecommerce-devops-projects/master/index.html -o /tmp/shopeasy-deploy/index.html","curl -fL https://raw.githubusercontent.com/nutankumari181121-gif/ecommerce-devops-projects/master/script.js -o /tmp/shopeasy-deploy/script.js","curl -fL https://raw.githubusercontent.com/nutankumari181121-gif/ecommerce-devops-projects/master/style.css -o /tmp/shopeasy-deploy/style.css","curl -fL https://raw.githubusercontent.com/nutankumari181121-gif/ecommerce-devops-projects/master/smartwatch.png -o /tmp/shopeasy-deploy/smartwatch.png","sudo cp /tmp/shopeasy-deploy/index.html /usr/share/nginx/html/index.html","sudo cp /tmp/shopeasy-deploy/script.js /usr/share/nginx/html/script.js","sudo cp /tmp/shopeasy-deploy/style.css /usr/share/nginx/html/style.css","sudo cp /tmp/shopeasy-deploy/smartwatch.png /usr/share/nginx/html/smartwatch.png","sudo systemctl reload nginx"]' \
            --region eu-north-1