name: Deploy ShopEasy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

         - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to EC2
        run:  |
          aws ssm send-command \
            --instance-ids i-03d9f6644b43993b8 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["echo ShopEasy deployment started successfully!"]' \
            --region eu-north-1